CREATE TABLE IF NOT EXISTS glossary (
  `id`          INT(11) NOT NULL AUTO_INCREMENT,
  `home`        VARCHAR(255) NULL DEFAULT NULL,
  `login`       VARCHAR(255) NULL DEFAULT NULL,
  `logout`      VARCHAR(255) NULL DEFAULT NULL,
  `control`     VARCHAR(255) NULL DEFAULT NULL,
  `notFound`    VARCHAR(255) NULL DEFAULT NULL,
  `tags`        VARCHAR(255) NULL DEFAULT NULL,
  `trending`    VARCHAR(255) NULL DEFAULT NULL,
  `lists`       VARCHAR(255) NULL DEFAULT NULL,
  `createdAt`   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt`   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY(id) REFERENCES language (id)

    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
