CREATE TABLE language (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order` INT NULL DEFAULT '10000',
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `isDefault` TINYINT(1) NULL DEFAULT NULL,
  `slug` VARCHAR(255) NULL DEFAULT 'en',
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `slug` (`slug` ASC)
);