CREATE TABLE IF NOT EXISTS user (
  `id` CHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `name` VARCHAR(255) UNIQUE NULL DEFAULT NULL,
  `level` ENUM('admin', 'user') NOT NULL DEFAULT 'user',
  `email` VARCHAR(255) UNIQUE NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `status` ENUM('inactive', 'active', 'disabled', 'removed') NOT NULL DEFAULT 'inactive',
  `statement` VARCHAR(255) NULL DEFAULT NULL,
  `location` VARCHAR(255) NULL DEFAULT NULL,
  `order` INT(11) NULL DEFAULT '10000',
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);