DROP PROCEDURE IF EXISTS language_get_one;

-- DELIMITER $$

CREATE PROCEDURE language_get_one(
  IN $SLUG VARCHAR(4)
)

BEGIN

 SELECT
    l.id,
    l.order,
    l.name,
    l.isDefault,
    l.slug,
    l.createdAt,
    l.updatedAt,
    JSON_OBJECT(
      'home', g.home,
      'login', g.login,
      'logout', g.logout,
      'control', g.control,
      'notFound', g.notFound,
      'tags', g.tags,
      'trending', g.trending,
      'lists', g.lists,
      'allBookmarks', g.allBookmarks,
      'myBookmarks', g.myBookmarks,
      'bookmarks', g.bookmarks,
      'links', g.links,
      'myUser', g.myUser,
      'users', g.users,
      'followers', g.followers,
      'following', g.following,
      'since', g.since,
      'serverError', g.serverError,
      'myTags', g.myTags,
      'myLists', g.myLists,
      'created', g.created,
      'updated', g.updated,
      'members', g.members,
      'addToList', g.addToList,
      'selectTags', g.selectTags,
      'allLists', g.allLists,
      'addBookmark', g.addBookmark,
      'forgotPassword', g.forgotPassword,
      'passwordForgotten', g.passwordForgotten,
      'nameOrEmail', g.nameOrEmail,
      'rememberIt', g.rememberIt,
      'dontHaveAccount', g.dontHaveAccount,
      'signUp', g.signUp,
      'create', g.create,
      'resetPassword', g.resetPassword,
      'extension', g.extension,
      'bookmarked', g.bookmarked,
      'date', g.date,
      'search', g.search,
      'newList', g.newList,
      'isPublic', g.isPublic,
      'notes', g.notes,
      'title', g.title,
      'save', g.save,
      'listName', g.listName,
      'listDescription', g.listDescription,
      'removeList', g.removeList,
      'myProfile', g.myProfile,
      'allUsers', g.allUsers,
      'name', g.name,
      'addList', g.addList,
      'totalBookmarks', g.totalBookmarks,
      'seeMore', g.seeMore,
      'weDidNotFindAnyList', g.weDidNotFindAnyList,
      'weDidNotFindAnyBookmark', g.weDidNotFindAnyBookmark,
      'password', g.password,
      'enter', g.enter,
      'exit', g.exit,
      'accept', g.accept,
      'reject', g.reject,
      'docs', g.docs,
      'privateBookmarks', g.privateBookmarks,
      'publicBookmarks', g.publicBookmarks,
      'deleteUser', g.deleteUser,
      'thisActionCanNotBeUndone', g.thisActionCanNotBeUndone,
      'delete', g.delete,
      'weDidNotFindAnyUser', g.weDidNotFindAnyUser,
      'thisUserHasNoBookmarksYet', g.thisUserHasNoBookmarksYet,
      'addUser', g.addUser,
      'userLists', g.userLists,
      'updateBookmark', g.updateBookmark,
      'weUseACookie', g.weUseACookie,
      'weDoNotShareIt', g.weDoNotShareIt,
      'youCanFindAllTheInfoAt', g.youCanFindAllTheInfoAt,
      'thePolicyPage', g.thePolicyPage,
      'editList', g.editList,
      'leaveList', g.leaveList,
      'allTags', g.allTags,
      'repeatPassword', g.repeatPassword,
      'email', g.email,
      'alreadyHaveAnAccount', g.alreadyHaveAnAccount,
      'userBookmarks', g.userBookmarks,
      'userTags', g.userTags,
      'deleteConfirmMessage', g.deleteConfirmMessage,
      'connection', g.connection,
      'connections', g.connections,
      'updateList', g.updateList,
      'createList', g.createList,
      'isPublicFem', g.isPublicFem
    ) glossary
  FROM language l
  INNER JOIN glossary g ON l.id = g.id
  WHERE l.slug = $SLUG;

END

-- DELIMITER ;