export const DEFAULT_PAGE_SIZE = 20;
export const DEFAULT_SORT_FIELD = 'id';
export const DEFAULT_LANGUAGE = 'en';
export const DEFAULT_REQUEST_TIMEOUT = 3000;
export const MS_30_MINS = 1000 * 60 * 30;
export const USER_BASIC_BOOKMARKS_PRIVATE_FREE_LIMIT = 50;
export const USER_BASIC_BOOKMARKS_PRIVATE_RATIO_LIMIT = 10;
