import { Link } from '@domain/link/entities/Link';
import { IListCreateResponseDTO } from '@domain/list/dto/IListCreateResponseDTO';
import { IListDeleteRequestDTO } from '@domain/list/dto/IListDeleteRequestDTO';
import { IListDeleteResponseDTO } from '@domain/list/dto/IListDeleteResponseDTO';
import { IListGetAllResponseDTO } from '@domain/list/dto/IListGetAllResponseDTO';
import { IListGetOneRequestDTO } from '@domain/list/dto/IListGetOneRequestDTO';
import { IListGetOneResponseDTO } from '@domain/list/dto/IListGetOneResponseDTO';
import { IListLinkDeleteRequestDTO } from '@domain/list/dto/IListLinkDeleteRequestDTO';
import { IListLinkDeleteResponseDTO } from '@domain/list/dto/IListLinkDeleteResponseDTO';
import { IListLinkGetAllRequestDTO } from '@domain/list/dto/IListLinkGetAllRequestDTO';
import { IListUpdateRequestDTO } from '@domain/list/dto/IListUpdateRequestDTO';
import { IListUpdateResponseDTO } from '@domain/list/dto/IListUpdateResponseDTO';
import { IListUserDeleteRequestDTO } from '@domain/list/dto/IListUserDeleteRequestDTO';
import { IListUserDeleteResponseDTO } from '@domain/list/dto/IListUserDeleteResponseDTO';
import { IListUserGetAllRequestDTO } from '@domain/list/dto/IListUserGetAllRequestDTO';
import { IListUserGetAllResponseDTO } from '@domain/list/dto/IListUserGetAllResponseDTO';
import { IListUserGetOneResponseDTO } from '@domain/list/dto/IListUserGetOneResponseDTO';
import { IListUserUpdateRequestDTO } from '@domain/list/dto/IListUserUpdateRequestDTO';
import { IListUserUpdateResponseDTO } from '@domain/list/dto/IListUserUpdateResponseDTO';
import { Tag } from '@domain/Tag/entities/Tag';
import { IListLinkCreateRequest } from './types/IListLinkCreateRequest';
import { IListLinkCreateResponse } from './types/IListLinkCreateResponse';
import { IListLinkGetOneRequest } from './types/IListLinkGetOneRequest';
import { IListLinkGetOneResponse } from './types/IListLinkGetOneResponse';

export interface IListRepo {
  listGetOne: (listGetOneRequestDTO: IListGetOneRequestDTO) => Promise<IListGetOneResponseDTO>;
  listGetAll: () => Promise<IListGetAllResponseDTO>;
  listCreate: (listCreateRequestDTO: { name: string; description: string; isPrivate: boolean; userId: string }) => Promise<IListCreateResponseDTO>;
  listUpdate: (listUpdateRequestDTO: IListUpdateRequestDTO) => Promise<IListUpdateResponseDTO>;
  listDelete: (listDeleteRequestDTO: IListDeleteRequestDTO) => Promise<IListDeleteResponseDTO>;
  listLinkGetOne: (listLinkGetOneRequestDTO: IListLinkGetOneRequest) => Promise<IListLinkGetOneResponse>;
  listLinkGetAll: (listLinkGetAllRequestDTO: IListLinkGetAllRequestDTO) => Promise<Link[]>;
  listLinkCreate: (listLinkCreateRequestDTO: IListLinkCreateRequest) => Promise<IListLinkCreateResponse>;
  listLinkDelete: (listLinkDeleteRequestDTO: IListLinkDeleteRequestDTO) => Promise<IListLinkDeleteResponseDTO>;
  listTagGetAll: (listTagGetAllRequestDTO) => Promise<Tag[]>;
  listUserGetOne: (listUserGetOneRequestDTO: { listId: number; userId: string }) => Promise<IListUserGetOneResponseDTO>;
  listUserGetAll: (listUserGetAllRequestDTO: IListUserGetAllRequestDTO) => Promise<IListUserGetAllResponseDTO>;
  listUserUpdate: (listUserUpdateRequestDTO: IListUserUpdateRequestDTO) => Promise<IListUserUpdateResponseDTO>;
  listUserCreate: (listUserCreateRequestDTO: { listId: number; userId: string }) => Promise<{ listId: number; userId: string }>;
  listUserDelete: (listUserDeleteRequestDTO: IListUserDeleteRequestDTO) => Promise<IListUserDeleteResponseDTO>;
}
