import { IListCreateRequestDTO } from '@domain/list/dto/IListCreateRequestDTO';
import { IListCreateResponseDTO } from '@domain/list/dto/IListCreateResponseDTO';
import { IListDeleteRequestDTO } from '@domain/list/dto/IListDeleteRequestDTO';
import { IListDeleteResponseDTO } from '@domain/list/dto/IListDeleteResponseDTO';
import { IListGetAllResponseDTO } from '@domain/list/dto/IListGetAllResponseDTO';
import { IListGetOneRequestDTO } from '@domain/list/dto/IListGetOneRequestDTO';
import { IListGetOneResponseDTO } from '@domain/list/dto/IListGetOneResponseDTO';
import { IListLinkCreateRequestDTO } from '@domain/list/dto/IListLinkCreateRequestDTO';
import { IListLinkCreateResponseDTO } from '@domain/list/dto/IListLinkCreateResponseDTO';
import { IListLinkDeleteRequestDTO } from '@domain/list/dto/IListLinkDeleteRequestDTO';
import { IListLinkDeleteResponseDTO } from '@domain/list/dto/IListLinkDeleteResponseDTO';
import { IListLinkGetAllRequestDTO } from '@domain/list/dto/IListLinkGetAllRequestDTO';
import { IListLinkGetAllResponseDTO } from '@domain/list/dto/IListLinkGetAllResponseDTO';
import { IListLinkGetOneRequestDTO } from '@domain/list/dto/IListLinkGetOneRequestDTO';
import { IListLinkGetOneResponseDTO } from '@domain/list/dto/IListLinkGetOneResponseDTO';
import { IListUpdateRequestDTO } from '@domain/list/dto/IListUpdateRequestDTO';
import { IListUpdateResponseDTO } from '@domain/list/dto/IListUpdateResponseDTO';
import { IListUserDeleteRequestDTO } from '@domain/list/dto/IListUserDeleteRequestDTO';
import { IListUserDeleteResponseDTO } from '@domain/list/dto/IListUserDeleteResponseDTO';
import { IListUserGetAllRequestDTO } from '@domain/list/dto/IListUserGetAllRequestDTO';
import { IListUserGetAllResponseDTO } from '@domain/list/dto/IListUserGetAllResponseDTO';
import { IListUserGetOneRequestDTO } from '@domain/list/dto/IListUserGetOneRequestDTO';
import { IListUserGetOneResponseDTO } from '@domain/list/dto/IListUserGetOneResponseDTO';
import { IListUserUpdateRequestDTO } from '@domain/list/dto/IListUserUpdateRequestDTO';
import { IListUserUpdateResponseDTO } from '@domain/list/dto/IListUserUpdateResponseDTO';
import { Tag } from '@domain/Tag/entities/Tag';

export interface IListRepo {
  listGetOne: (listGetOneRequestDTO: IListGetOneRequestDTO) => Promise<IListGetOneResponseDTO>;
  listGetAll: () => Promise<IListGetAllResponseDTO>;
  listCreate: (listCreateRequestDTO: IListCreateRequestDTO) => Promise<IListCreateResponseDTO>;
  listUpdate: (listUpdateRequestDTO: IListUpdateRequestDTO) => Promise<IListUpdateResponseDTO>;
  listDelete: (listDeleteRequestDTO: IListDeleteRequestDTO) => Promise<IListDeleteResponseDTO>;
  listLinkGetOne: (listLinkGetOneRequestDTO: IListLinkGetOneRequestDTO) => Promise<IListLinkGetOneResponseDTO>;
  listLinkGetAll: (listLinkGetAllRequestDTO: IListLinkGetAllRequestDTO) => Promise<IListLinkGetAllResponseDTO>;
  listLinkCreate: (listLinkCreateRequestDTO: IListLinkCreateRequestDTO) => Promise<IListLinkCreateResponseDTO>;
  listLinkDelete: (listLinkDeleteRequestDTO: IListLinkDeleteRequestDTO) => Promise<IListLinkDeleteResponseDTO>;
  listTagGetAll: (listTagGetAllRequestDTO) => Promise<Tag[]>;
  listUserGetOne: (listUserGetOneRequestDTO: IListUserGetOneRequestDTO) => Promise<IListUserGetOneResponseDTO>;
  listUserGetAll: (listUserGetAllRequestDTO: IListUserGetAllRequestDTO) => Promise<IListUserGetAllResponseDTO>;
  listUserUpdate: (listUserUpdateRequestDTO: IListUserUpdateRequestDTO) => Promise<IListUserUpdateResponseDTO>;
  listUserDelete: (listUserDeleteRequestDTO: IListUserDeleteRequestDTO) => Promise<IListUserDeleteResponseDTO>;
}
